### ISSUE TITLE
networkx version control is to strict

### ISSUE THREAD

**Issue by gryBox** [gte620v/pyd3netviz#1]
Hi - While installing `pyd3netviz` my install of `networkx 2.0` was downgraded to 'nx 1.11` .
Maybe the requirements could be changed?

Thanks

BTW: 

- How does one import d3 not from file? something like this `src="https://d3js.org/d3.v4.min.js"`. 
- I really like this package

**Comment by gte620v** [comment]
Thanks for your interest!  I just updated the setup.py to require networkx 2.1 in #2.

I am not sure what is required to import d3 without using the file...
